// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NewPostFormController from "./new_post_form_controller"
application.register("new-post-form", NewPostFormController)

import UppyFileUploadController from "./uppy_file_upload_controller"
application.register("uppy-file-upload", UppyFileUploadController)
